accounts/urls.py
from django.urls import path
from .views import signup_view,login_view
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name="login"),
    path('signup', signup_view, name="signup"),
    #path('logout',logout_view, name="logout"),
    path('logout/',auth_views.LogoutView.as_view(template_name='accounts/logout.html'),name='logout'),
]

digitalmenu/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include
from django.conf import settings
from django.conf.urls import handler404,handler500
from menucard import views
import clearcache


urlpatterns = [
    path('admin/clearcache/',include('clearcache.urls')),
    path('admin/', admin.site.urls), # admin url changed to digitalmenu
    path('',include('menucard.urls'),name='menucard'),
    path('accounts/', include('accounts.urls'),name='accounts'),
    path('upload/',include('upload.urls'),name='upload'),
    path('__debug__/', include('debug_toolbar.urls')),

]

handler404 = views.error_404
handler500 = views.error_500


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

menucard/urls.py
from django.contrib import admin
from django.urls import path

from .views import ( landing,newMenuDisplayJson)


app_name = "menucard"
urlpatterns = [
    
    path('',landing , name='landing'),   
    path('<str:header>/',newMenuDisplayJson , name='itemjson'), 
        
   
    
]

upload/urls.py
from django.urls import path 
from .views import upload_file_view

app_name='upload'

urlpatterns = [
    path ('file',upload_file_view,name='upload-view')
]

menucard/models.py
from django.db import models
#from django.conf import settings
from django.shortcuts import reverse
#from django.utils import timezone
from django.contrib.auth.models import User
#from PIL import Image

# Create your models here.

class Hotel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,blank=True)
    name= models.CharField(max_length=100,blank=True)
    header=models.CharField(max_length=50,blank=True)
    address=models.CharField(max_length=250,blank=True)
    bgcolor= models.CharField(max_length=100,blank=True)
    mobile=models.CharField(max_length=100,blank=True)
    whatsapplink=models.CharField(max_length=100,blank=True)
    mycolor= models.CharField(max_length=100,blank=True)
    catcolor=models.CharField(max_length=100,blank=True)
    bordercolor=models.CharField(max_length=100,blank=True)
    specialheading=models.CharField(max_length=250,blank=True)
    bgimage = models.ImageField(upload_to='images/',blank=True,null=True)
    pureveg=models.BooleanField(default=True)
    message1=models.CharField(max_length=250,blank=True)
    message2=models.CharField(max_length=250,blank=True)

    def __str__(self):
        return self.name
    
class Category(models.Model):
    title = models.CharField(max_length=225)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    hotel=models.ForeignKey(Hotel,on_delete=models.CASCADE,blank=True)
    active=models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Categories"
       

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

    @property
    def get_products(self):
     return Item.objects.filter(categories__title=self.title)

class Item(models.Model):

    TYPE=(
        
        ('VEG','VEG'),
        ('NON-VEG','NON-VEG'),
        
        )
    LABELS = (
        ('Recommended', 'Recommended'),
        ('Special', 'Special'),
        ('Offer', 'Offer'),
    )   
    
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=250,blank=True)
    price = models.CharField(max_length=250,blank=True)
    image = models.ImageField(upload_to='images/',blank=True,null=True)
    type= models.CharField(max_length=25, choices=TYPE, blank=True)
    categories = models.ForeignKey(Category, related_name='Category', blank=True, on_delete=models.CASCADE)
    label = models.CharField(max_length=15, choices=LABELS, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    hotel=models.ForeignKey(Hotel,on_delete=models.CASCADE,blank=True)
    active=models.BooleanField(default=True,blank=False)
    

    def __str__(self):
        return self.title
       

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

   
    

   



menucard/views.py
from .models import Category, Hotel,Item
from django.db.models import Q
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from menucard.menu_mixin import MainView
from json import dumps

# Create your views here.

def landing(request):    
    return render(request, 'menucard/landing.html')

# @cache_page(60*60)

def error_404(request,exception=None):
        data = {}
        return render(request,'menucard/error_404.html', data)

def error_500(request,exception=None):
        data = {}
        return render(request,'menucard/error_500.html', data)

def newMenuDisplayJson(request,header):    
    hotel=Hotel.objects.get(header=header)
    check1=Q(hotel_id=hotel.id)
    check2=Q(active=True)
    check3=Q(Category__active=True)   
    #filtering base on veg non veg and all  
    menu=MainView(check1,check2,check3)
    details=menu.allitem()      
    image_url={item.id:item.image.url for cat in details for item in cat.Category.all() if item.image }
    cat=list(details.values())
    finalcat=dumps(cat)  
    items=Item.objects.all().filter(hotel_id=hotel.id).values() 
    items=list(items)
    for i in items:
        for image in image_url:
            if i['id']==image:
                i['image']=image_url[i['id']]                
     
    finalitem=dumps(items)
    context= {"hotel":hotel,"details":details,"cat":finalcat,"item":finalitem}
    return render(request, 'menucard/newmenuJson.html', context)


menucard/templates/menucard/base.html
{% load static %}



<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

 
    {% block title %}
    <title>
    
    Digital Menu</title>

    {% endblock title %}
  <meta content="" name="description">
  <meta content="" name="keywords">



  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
<link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href=" {% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/img/logo.png' %}" rel="icon" type="image/x-icon">
  <script src="https://unpkg.com/htmx.org@1.7.0" integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" crossorigin="anonymous"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" />
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/jquery-ui.js" type="text/javascript"></script>
  <script src="https://unpkg.com/htmx.org@1.7.0" integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" crossorigin="anonymous"></script>
  <link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/themes/blitzer/jquery-ui.css" rel="stylesheet"
      type="text/css" />
      

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Restaurantly - v3.1.0
  * Template URL: https://bootstrapmade.com/restaurantly-restaurant-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<style> 
h1, h2, h3, h4, h5, h6 {
    margin-top: 20px;
    
}

</style>

<body> 

    {% block content %}

    
    {% endblock %}




  <!-- Template Main JS File -->
  
  <script src="{% static 'assets/js/main.js' %}"></script>
  


</body>

</html>    

menucard/templates/menucard/customcss.html
{% extends "menucard/base.html" %}

{% block content %}

<style>
  
    :root {
      --bg-color:{{ hotel.bgcolor }} !IMPORTANT ;
      --my-color:{{ hotel.mycolor }} !IMPORTANT ;
      --cat-color:{{ hotel.catcolor }} !IMPORTANT;
      --border-color:{{ hotel.bordercolor }} !IMPORTANT;
  
    }
    body {
      font-size: 14px;
      background: var(--bg-color);
    }
  
    #hero {
      width: 100%;
      height: 30vh;
      filter: brightness(180%);
      background-size: cover;
      position: relative;
      padding: 0;
    }

    
  
    .section-bg {
      background-color: var(--bg-color);
    }
  
    .cateogery {
      color: var(--cat-color);
      font-size: 20px;
    }
  
    .menu .menu-content span {
      background: var(--bg-color);
    }
  
  
    .box-shadow {
      border-radius: 5px;
      background: var(--bg-color);
      box-shadow:1px 4px var(--border-color);
      -webkit-box-shadow: 1px 4px var(--border-color);
  
    }
  
    .section-title p {
      color: var(--my-color);
    }
  
    .menu .menu-ingredients {
  
      color: var(--my-color);
  
    }

.imageContainer > img:hover {
  
  width: 150px;
  height: 150px;
  z-index: 10;
  position: relative;
  
  
  transition: 0.25s ease;
 
}


    
  form {
    display: inline-flex;
    justify-content: center;
    align-items: center;
    padding-bottom: .2rem;
    padding-top: .2rem;
    position: relative;

  }

    .veggreen{
      color:#00FF00 ;

    }

    .nonvegred{

      color: red;

    }
  
    .btn:active {
      background-color: orange;
      box-shadow: 0 5px gray;
      transform: translateY(2px);
    }

    
.menu .menu-item {
  margin-top: 5px;
}

.menu .menu-img {
  width: 70px;
  border-radius: 50%;
  float: right;
  border: 3px solid rgba(255, 255, 255, 0.2);
}
  
    .btn-sm {
  
  
      padding-top: .1rem;
      padding-left: .1rem;
      padding-right: .1rem;
      padding-bottom: .1rem;
      font-size: .7rem;
      line-height: 1.5;
    }

    @media only screen and (max-width: 600px){
    .imageContainer > img:hover {
  
  /* width: 200px;
  height: 150px; */
  z-index: 10;
  position: relative;
  
  transform: scale(1.5);
  transition: 0.25s ease;
  margin-right: 50px;
 
}
    }

  </style>


    
{% endblock content%}

menucard/templates/menucard/customheader.html
{% extends "menucard/base.html" %}

{% block content %}

{% include "menucard/customcss.html" %}


<section id="hero" style="background: url('{{hotel.bgimage.url}}')  top center;width: 100%;
              height: 30vh;   filter: brightness(180%); background-size: cover;position: relative;
              padding: 0; " class="d-flex align-items-center">

    <div class="container position-relative text-left text-lg-start" data-aos="zoom-in" data-aos-delay="100">
      <div class="row">
        <div class="col-lg-6 " style="margin-top: 15px;">
          <h5> <span style="text-shadow: 2px 2px 4px #000000;">{{hotel.name}}</span></h5>
          <div style="text-shadow: 2px 2px 4px #000000; font-size: 10px;padding-bottom: 15px;">{{hotel.address}}</div>
        </div>
  
      </div>
    </div>
  </section><!-- End Hero data-aos="fade-up" data-aos-delay="200" -->

  {% endblock content%}

menucard/templates/menucard/error_404.html
{% extends "menucard/base.html" %}

{% block content %}

 <!-- ======= Top Bar ======= -->
 <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex justify-content-center justify-content-md-between">

      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-phone d-flex align-items-center"><span>+91 7306191467</span></i>
        

    </div>
  </div>
  </div>

  <!-- ======= Header ======= -->

  <header id="header" class="fixed-top d-flex align-items-cente">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">

      <h1 class="logo me-auto me-lg-0"><a href="{% url 'menucard:landing' %}">Digital Menu</a>
      
        <br><span style="font-size: small;"  >
          {% if user.is_authenticated %}
          Welcome {{user.username}}
          {% endif %}
        </span>
      </h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      
      <nav id="navbar" class="navbar order-last order-lg-0">
       
        <ul>
         <!-- {% if user.is_authenticated %}
            <li><a class="nav-link scrollto active" href="{% url 'menucard:item-create' %}">Create Item</a></li>
            <li><a class="nav-link scrollto active" href="{% url 'menucard:item_list' %}"> View Item</a></li>
            {% endif %}
            {% if not user.is_authenticated %}
          <li><a class="nav-link scrollto active" href="{% url 'accounts:login' %}">Login</a></li>
          {% endif %}
          {% if user.is_authenticated %}
          <li><a class="nav-link scrollto" href="{% url 'accounts:logout' %}">Logout</a></li>
          {% endif %}-->
          


       {% if user.is_authenticated %}
          <li><a class="nav-link scrollto" href="/admin/logout">Logout</a></li>
          <li><a class="nav-link scrollto" href="/admin">Go to Items</a></li>
        {% else %}
        <li><a class="nav-link scrollto" href="/admin">Login</a></li>
        {% endif %}

          <li><a class="nav-link scrollto" href="#menu">Contact</a></li>
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
      

    </div>
  

  </header><!-- End Header -->
  <br><br><br><br><br><br>

   <!-- ======= Why Us Section ======= -->
   <section id="why-us" class="why-us">
    <div class="container" data-aos="fade-up">

</h6><div class="notfound-page">
    <div class="wrapper">
      <h5>Ohh!! Receipe Not found</h5>
      <h5>Please check the address entered </h5>


      <div class="buttons">

        <a href="{% url 'menucard:landing' %}"><i class="fas fa-home"></i> Go to Home</a>
        
      </div>

{% endblock content %}

menucard/templates/menucard/error_500.html
{% extends "menucard/base.html" %}

{% block content %}

 <!-- ======= Top Bar ======= -->
 <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex justify-content-center justify-content-md-between">

      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-phone d-flex align-items-center"><span>+91 7306191467</span></i>
        

    </div>
  </div>
  </div>

  <!-- ======= Header ======= -->

  <header id="header" class="fixed-top d-flex align-items-cente">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">

      <h1 class="logo me-auto me-lg-0"><a href="{% url 'menucard:landing' %}">Digital Menu</a>
      
        <br><span style="font-size: small;"  >
          {% if user.is_authenticated %}
          Welcome {{user.username}}
          {% endif %}
        </span>
      </h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      
      <nav id="navbar" class="navbar order-last order-lg-0">
       
        <ul>
         <!-- {% if user.is_authenticated %}
            <li><a class="nav-link scrollto active" href="{% url 'menucard:item-create' %}">Create Item</a></li>
            <li><a class="nav-link scrollto active" href="{% url 'menucard:item_list' %}"> View Item</a></li>
            {% endif %}
            {% if not user.is_authenticated %}
          <li><a class="nav-link scrollto active" href="{% url 'accounts:login' %}">Login</a></li>
          {% endif %}
          {% if user.is_authenticated %}
          <li><a class="nav-link scrollto" href="{% url 'accounts:logout' %}">Logout</a></li>
          {% endif %}-->
          


       {% if user.is_authenticated %}
          <li><a class="nav-link scrollto" href="/admin/logout">Logout</a></li>
          <li><a class="nav-link scrollto" href="/admin">Go to Items</a></li>
        {% else %}
        <li><a class="nav-link scrollto" href="/admin">Login</a></li>
        {% endif %}

          <li><a class="nav-link scrollto" href="#menu">Contact</a></li>
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
      

    </div>
  

  </header><!-- End Header -->
  <br><br><br><br><br><br>

   <!-- ======= Why Us Section ======= -->
   <section id="why-us" class="why-us">
    <div class="container" data-aos="fade-up">

</h6><div class="notfound-page">
    <div class="wrapper">
      <h5>Ohh!! Receipe Not found</h5>
      <h5>Please check the address entered </h5>


      <div class="buttons">

        <a href="{% url 'menucard:landing' %}"><i class="fas fa-home"></i> Go to Home</a>
        
      </div>

{% endblock content %}

menucard/templates/menucard/landing.html
{% extends "menucard/base.html" %}

{% block content %}

 <!-- ======= Top Bar ======= -->
 <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex justify-content-center justify-content-md-between">

      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-phone d-flex align-items-center"><span>+91 7306191467</span></i>
 

    </div>
  </div>
  </div>

  <!-- ======= Header ======= -->

  <header id="header" class="fixed-top d-flex align-items-cente">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">

      <h1 class="logo me-auto me-lg-0"><a href="{% url 'menucard:landing' %}">Digital Menu</a>
      
        <br><span style="font-size: small;"  >
          {% if user.is_authenticated %}
          Welcome {{user.username}}
          {% endif %}
        </span>
      </h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      
      <nav id="navbar" class="navbar order-last order-lg-0">
       
        <ul>
       
       {% if user.is_authenticated %}
          <li><a class="nav-link scrollto" href="/admin/logout">Logout</a></li>
          <li><a class="nav-link scrollto" href="/admin">Go to Items</a></li>
        {% else %}
        <li><a class="nav-link scrollto" href="/admin">Login</a></li>
        {% endif %}

          <li><a class="nav-link scrollto" href="#menu">Contact</a></li>
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
      

    </div>
  

  </header><!-- End Header -->
  <br><br><br><br><br><br>

   <!-- ======= Why Us Section ======= -->
   <section id="why-us" class="why-us">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>Why Us</h2>
        <!--p>Why Choose Our Restaurant</p-->
      </div>

      <div class="row">

        <div class="col-lg-4">
          <div class="box" data-aos="zoom-in" data-aos-delay="100">
            <span>01</span>
            <a href="https://www.datomation.co.in"> <h4>Dashboards</h4></a>
            <p></p>
          </div>
        </div>

        <div class="col-lg-4 mt-4 mt-lg-0">
          <div class="box" data-aos="zoom-in" data-aos-delay="200">
            <span>02</span>
            <a href="https://www.datomation.co.in"><h4>SM  Management</h4></a>
            <p> </p>
          </div>
        </div>

        <div class="col-lg-4 mt-4 mt-lg-0">
          <div class="box" data-aos="zoom-in" data-aos-delay="300">
            <span>03</span>
            <a href="https://www.datomation.co.in"> <h4> Web Development </h4></a>
            <p></p>
          </div>
        </div>

      </div>

    
  </section><!-- End Why Us Section -->


{% endblock content %}

menucard/templates/menucard/newmenuJson.html
{% extends "menucard/base.html" %}

{% block title %}
<title>

  {{ hotel.name}}</title>

{% endblock title %}

{% block content %}

{% include "menucard/customcss.html" %}
{% include "menucard/customheader.html" %}


  <section id="menu" class="menu section-bg">
    <div class="container">
  
      <div class="section-title ">
        <div class="header" id="myHeader" style="width: 60%;float: right; overflow: hidden ">
          <div class="sb-example-1">
            <div class="search">
              <input id="filter" type="text" class="searchTerm" placeholder="What are you looking for?">
              <button type="submit" class="searchButton">
                <i class="fa fa-search" style="color: lightgrey;"></i>
              </button>
            </div>
          </div>
        </div>
        <p id="recommended"> Menu</p>
        
        {% if hotel.pureveg %}
        <button id="veg" type="submit" class="btn btn-success btn-sm active"
        style="border-radius: 50%;box-shadow: 0px 4px green" value="" name="type">veg</button>
        {% else %}
  
        <form id='all' action="">
          <input id='allbutton' type="submit" value="&nbsp;all&nbsp;" class="btn btn-warning btn-sm active" style="border-radius: 50%;box-shadow: 0px 4px white"; >
        </form>
  
  
        <form id='veg' action="">
    <input id='vegbutton' type="submit" value="veg" class="btn btn-light btn-sm active"
    style="border-radius: 50%;box-shadow: 0px 4px white">
  </form>

  <form id='non-veg' action="">
    <input id='nonvegbutton' type="submit" value="non" class="btn btn-light btn-sm active "
    style="border-radius: 50%;box-shadow: 0px 4px white" >
  </form>

  
  {% endif %}

  </div>
  <div id="results">
    <div class="cateogery" data-aos="zoom-in" data-aos-delay="100"> {{hotel.specialheading}} </div>
    {% for category in details %}
    <div id="results" class="row menu-container box-shadow" >
      {% for item in category.Category.all %}
      {% if item.label %}
      <div class="col-lg-6 menu-item filter-starters imageContainer" data-aos="zoom-in" data-aos-delay="100">
        {% if item.image %}
        <img src="{{item.image.url }}" class="menu-img largeimg" alt="">
        {% endif %}
        
        <i class="bi bi-stop-btn {%if item.type == 'NON-VEG' %} nonvegred {% else %} veggreen {% endif %} " style="font-size: 15px;bottom:2px;margin-left:10px;"></i>
        <div class="menu-content">
          <span style="background: var(--bg-color);color: var(--my-color);"> {{item.title}} </span> <span
            style="background: var(--bg-color);color: var(--my-color);">
            {% if item.price == 'APS' %} {{item.price}} {% else %} ₹{{item.price}} {% endif %}</span>

        </div>          

        <div class="menu-ingredients">
          {{item.description}}
        </div>

      </div>      

      
      {% endif %}
      {% endfor %}
    </div>
    {% endfor %}
  </div>



  <div id='result1'>
    {% for category in details %}

    <div id="results">
      <div id="{{category}}" class="cateogery" data-aos="zoom-in" data-aos-delay="100" style="left: 20px;padding-top: 50px;
        margin-top: -25px;"> {{category}}</div>
      <!-- {{category}} ({{category.items_count}}) </div> -->
      <div class="row menu-container box-shadow" data-aos="zoom-in" data-aos-delay="100">

        {% for item in category.Category.all %}
        <!-- very very important -->
      
        <div class="col-lg-6 menu-item filter-starters imageContainer">
          {% if item.image %}
          <img src="{{item.image.url }}" class="menu-img largeimg" alt="">

          {% endif %}
          

          <i class="bi bi-stop-btn non-veg {%if item.type == 'NON-VEG' %} nonvegred {% else %} veggreen {% endif %}" style="font-size: 15px;bottom:2px;margin-left:10px;"></i>
          <div class="menu-content non-veg">
            <span style="background: var(--bg-color);;color: var(--my-color);"> {{item.title}} </span> <span
              style="background: var(--bg-color);color: var(--my-color);">
              {% if item.price == 'APS' %} {{item.price}} {% else %} ₹{{item.price}} {% endif %}</span>

          </div>          

          <div class="menu-ingredients">
            {{item.description}}
          </div>

        </div>       
        {% endfor %}
      </div>
      {% endfor %}

    </div>
  





  </div>
  

</div>
</section>
<!-- End Menu Section -->
<div class="myButtonContainer">
  <div id="mybutton" style="z-index: 9">
    <!--button class="feedback toggle">Browse Menu</button-->
    <input class="feedback" type="button" id="btnShow" style="z-index: 9" value="Browse Menu" />
    
    <div id="dialog" style="display: none;">
     
         
      <ul style="list-style:square; color:var(--my-color);">
        <li><a href="#recommended"><strong>RECOMMENDED</strong></a></li>
        {% for category in details %}

        <li><a href="#{{category}}">{{category}} <span
              style=" font-size: small;"><strong>({{category.items_count}})</strong></span></a></li>

        {% endfor %}
      </ul>
    </div>
    <div>
      <a href="{{hotel.whatsapplink}}" target="_blank"> <img src="/static/assets/img/wa1.png" id="wa" style="z-index: 9"
          alt=""></a>
    </div>
    <div>
      <a href="tel:{{hotel.mobile}}"> <img src="/static/assets/img/call.png" id="phone" style="z-index: 9" alt=""></a>

    </div>
  </div>
  
  
</div>

<p class="ml-3">{{hotel.message1}}</p>
<p class="ml-3">{{hotel.message2}}</p>
<br>
<br>
<br><br>
<!-- Vendor JS Files -->
<!-- serch function -->


{% include "menucard/customscript.html" %}
{% endblock %}