accounts/urls.py
from django.urls import path
from .views import signup_view,login_view
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name="login"),
    path('signup', signup_view, name="signup"),
    #path('logout',logout_view, name="logout"),
    path('logout/',auth_views.LogoutView.as_view(template_name='accounts/logout.html'),name='logout'),
]

digitalmenu/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include
from django.conf import settings
from django.conf.urls import handler404,handler500
from menucard import views
import clearcache


urlpatterns = [
    path('admin/clearcache/',include('clearcache.urls')),
    path('admin/', admin.site.urls), # admin url changed to digitalmenu
    path('',include('menucard.urls'),name='menucard'),
    path('accounts/', include('accounts.urls'),name='accounts'),
    path('upload/',include('upload.urls'),name='upload'),
    path('__debug__/', include('debug_toolbar.urls')),

]

handler404 = views.error_404
handler500 = views.error_500


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

menucard/urls.py
from django.contrib import admin
from django.urls import path

from .views import ( landing,newMenuDisplayJson)


app_name = "menucard"
urlpatterns = [
    
    path('',landing , name='landing'),   
    path('<str:header>/',newMenuDisplayJson , name='itemjson'), 
        
   
    
]

upload/urls.py
from django.urls import path 
from .views import upload_file_view

app_name='upload'

urlpatterns = [
    path ('file',upload_file_view,name='upload-view')
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUSerForm(UserCreationForm):
    email = forms.EmailField(required=True)
    phone_number = forms.CharField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "phone_number", "first_name", "last_name", "password1", "password2")

    def save(self,commit=True):
        user = super(NewUSerForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.phone_number = self.cleaned_data["phone_number"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user

accounts/views.py
from django.shortcuts import render, redirect,HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .forms import NewUSerForm

def signup_view(request):
    if request.method == 'POST':
        form = NewUSerForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('menucard:menu')
    else:
        form = NewUSerForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('menucard:landing')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

# def logout_view(request):
#     if request.method == 'POST':
#             logout(request)
#             return HttpResponseRedirect("logout")

accounts/templates/accounts/login.html
  

{% extends "menucard/base.html" %}
{% load crispy_forms_tags %} 

{% block content %}
<div class="container">
    <h1>Login</h1>
    <div class="form-border">
        <form class="site-form" action="{% url 'accounts:login' %}" method="post">
            <div class="logging-form">
                {% csrf_token %}
                {{ form|crispy }}
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <input type="submit" value="Login" class="btn btn-primary btn-md my-0 p" />
            </div>
        </form>
    </div>
    {% comment %}
      
   
    <p>Not got an account? <a href="{% url 'accounts:signup' %}"><u>Sign Up</u></a></p>

    {% endcomment %}
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "menucard/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<h2>You have been logged out</h2>        
        <div class="border-top pt-3">
            <small class="text-muted">
               <a href="{% url 'accounts:login' %}">Log in again</a><br>
               <a href="{% url 'menucard:landing' %}">Go back to Home</a>

            </small>

        </div>
  
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "menucard/base.html" %}
{% load crispy_forms_tags %} 
{% block content %}
<div class="container">
    <h1>Signup</h1>
    <div class="form-border">
        <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Signup" class="btn">
        </form>
    </div>
</div>
{% endblock %}